theme: jekyll-theme-leap-day
title: MLOps-Evaluation
description: A project specifying how to create and deploy models in the enterprise environment
email: meritxell.diaz@gmail.com
author: Meritxell DÃ­az Coque
socials:
  GitHub: https://github.com/meridiaz
